apiVersion: v1
kind: Service
metadata:
  name: metadata-service-service
  labels:
    app: metadata-service-app
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: metadata-service-app
  ports:
    - port: 8080
      targetPort: 8080
